#!/usr/bin/env bash
# =============================================================================
# OpenClaw Terminal Watcher
#
# Captures terminal output and periodically sends it to ChatGPT for insights.
# Writes summaries to a file that Claude Code can read on demand.
#
# Usage:
#   1. Source it to wrap your current shell:
#      source ~/openclaw/chatgpt-mcp/terminal-watcher.sh
#
#   2. Or pipe a specific command through it:
#      npm run build 2>&1 | ~/openclaw/chatgpt-mcp/terminal-watcher.sh --analyze
#
#   3. Read latest insights:
#      cat ~/openclaw/chatgpt-mcp/.terminal-insights.md
# =============================================================================

set -euo pipefail

INSIGHTS_FILE="${OPENCLAW_ROOT:-$HOME/openclaw}/chatgpt-mcp/.terminal-insights.md"
BUFFER_FILE="/tmp/openclaw-terminal-buffer.txt"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"
MODEL="${CHATGPT_TERMINAL_MODEL:-gpt-4o-mini}"
MAX_TOKENS=512
FLUSH_INTERVAL="${TERMINAL_WATCH_INTERVAL:-60}"  # seconds between analysis runs

if [ -z "$OPENAI_API_KEY" ]; then
  # Try loading from .env
  if [ -f "${OPENCLAW_ROOT:-$HOME/openclaw}/.env" ]; then
    export $(grep -E '^OPENAI_API_KEY=' "${OPENCLAW_ROOT:-$HOME/openclaw}/.env" | head -1)
  fi
fi

if [ -z "${OPENAI_API_KEY:-}" ]; then
  echo "[terminal-watcher] ERROR: OPENAI_API_KEY not set. Add it to ~/openclaw/.env"
  exit 1
fi

analyze_buffer() {
  local content
  content=$(cat "$BUFFER_FILE" 2>/dev/null || echo "")

  if [ -z "$content" ] || [ ${#content} -lt 20 ]; then
    return 0
  fi

  # Truncate if huge
  if [ ${#content} -gt 12000 ]; then
    content="${content:0:6000}

... [truncated] ...

${content: -6000}"
  fi

  local response
  response=$(curl -sS https://api.openai.com/v1/chat/completions \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -H "Content-Type: application/json" \
    -d "$(jq -n \
      --arg model "$MODEL" \
      --argjson max_tokens "$MAX_TOKENS" \
      --arg content "$content" \
      '{
        model: $model,
        max_tokens: $max_tokens,
        messages: [
          {
            role: "system",
            content: "You are a terminal watcher for OpenClaw. Analyze this terminal output and report: (1) errors or warnings, (2) notable patterns, (3) suggested actions. Be extremely concise — max 5 bullet points. If everything looks normal, say so in one line."
          },
          {
            role: "user",
            content: ("Recent terminal output:\n```\n" + $content + "\n```")
          }
        ]
      }')" 2>/dev/null)

  local analysis
  analysis=$(echo "$response" | jq -r '.choices[0].message.content // "Analysis unavailable"' 2>/dev/null)
  local tokens
  tokens=$(echo "$response" | jq -r '.usage.total_tokens // "?"' 2>/dev/null)

  # Write insights file (overwrite — always latest)
  cat > "$INSIGHTS_FILE" <<EOF
# Terminal Insights
**Updated:** $(date '+%Y-%m-%d %H:%M:%S')
**Model:** $MODEL | **Tokens:** $tokens

$analysis

---
*Auto-generated by terminal-watcher.sh. Claude Code can read this file anytime.*
EOF

  # Clear buffer after analysis
  > "$BUFFER_FILE"

  echo "[terminal-watcher] Insight written to $INSIGHTS_FILE ($tokens tokens)"
}

# Mode: --analyze (pipe mode — analyze stdin immediately)
if [ "${1:-}" = "--analyze" ]; then
  tee "$BUFFER_FILE"
  analyze_buffer
  exit 0
fi

# Mode: background watcher (source this file)
echo "[terminal-watcher] Starting background watcher (interval: ${FLUSH_INTERVAL}s)"
echo "[terminal-watcher] Insights file: $INSIGHTS_FILE"

# Set up the PROMPT_COMMAND to capture output
# This appends the last command's output to the buffer
export OPENCLAW_TERMINAL_BUFFER="$BUFFER_FILE"
> "$BUFFER_FILE"

# Background analysis loop
(
  while true; do
    sleep "$FLUSH_INTERVAL"
    analyze_buffer
  done
) &
WATCHER_PID=$!

echo "[terminal-watcher] Background PID: $WATCHER_PID"
echo "[terminal-watcher] To stop: kill $WATCHER_PID"

# Trap to clean up on shell exit
trap "kill $WATCHER_PID 2>/dev/null; echo '[terminal-watcher] Stopped.'" EXIT

# Helper function to manually flush
openclaw_analyze() {
  echo "[terminal-watcher] Running analysis now..."
  analyze_buffer
}

export -f openclaw_analyze 2>/dev/null || true

echo "[terminal-watcher] Tip: Run 'openclaw_analyze' to trigger immediate analysis"
echo "[terminal-watcher] Tip: Pipe commands with: command 2>&1 | tee -a $BUFFER_FILE"
