#!/bin/bash
# cron-idea-engine.sh — Perpetual Idea Engine
# Schedule: daily at 11:30pm (30 23 * * *)
# Produces: 10+ researched money-making ideas → outputs/ideas-{date}.md
# Sends: Tier-2 Telegram for Jordan morning review

OPENCLAW_ROOT="${HOME}/openclaw"
TODAY=$(date +%Y-%m-%d)
OUTPUT="${OPENCLAW_ROOT}/outputs/ideas-${TODAY}.md"

set -a; source "${OPENCLAW_ROOT}/.env" 2>/dev/null || true; set +a

# Don't re-run if today's file already exists with content
if [[ -f "$OUTPUT" ]] && [[ $(wc -l < "$OUTPUT") -gt 20 ]]; then
  exit 0
fi

# Throttle: slow down generation when pending backlog is large
PENDING_IDEAS=$(find "${OPENCLAW_ROOT}/ideas" -name "idea-*.json" -exec grep -l '"status": "pending"' {} \; 2>/dev/null | wc -l | tr -d ' ')
if [[ "$PENDING_IDEAS" -ge 100 ]]; then
  echo "[${TODAY}] Idea engine skipped — ${PENDING_IDEAS} pending ideas (hard cap 100)" >> "${OPENCLAW_ROOT}/memory/IDLE_LOG.md"
  exit 0
elif [[ "$PENDING_IDEAS" -ge 50 ]]; then
  # Only generate every 3rd day when backlog is 50-99
  DAY_OF_YEAR=$(date +%j)
  if [[ $((DAY_OF_YEAR % 3)) -ne 0 ]]; then
    echo "[${TODAY}] Idea engine throttled — ${PENDING_IDEAS} pending ideas (generating every 3rd day)" >> "${OPENCLAW_ROOT}/memory/IDLE_LOG.md"
    exit 0
  fi
fi

# --- Pull context ---
MEMORY=$(tail -50 "${OPENCLAW_ROOT}/memory/MEMORY.md" 2>/dev/null || echo "No memory")
PAST_IDEAS=$(ls "${OPENCLAW_ROOT}/outputs/ideas-"*.md 2>/dev/null | tail -5 | xargs grep "^##" 2>/dev/null | sed 's/.*##//' | head -30 || echo "None yet")
QUEUE=$(cat "${OPENCLAW_ROOT}/queue/pending.json" 2>/dev/null | python3 -c "import json,sys; d=json.load(sys.stdin); print('\n'.join([t.get('title','') for t in d[:10]]))" 2>/dev/null || echo "Empty")

# --- Generate ideas via LLM ---
PROMPT="You are Clawmpson, an AI business operator working for Jordan (Omega MegaCorp).
Jordan's goal: $10k/month net revenue from internet businesses, as fast as possible.
Current assets: Claude AI (BYOK), local Ollama LLMs, GitHub, meOS iOS app (in TestFlight), xyz.cards NFC card SaaS, OpenClaw agent stack.

Your job: generate exactly 10 SOLID, actionable money-making ideas for Jordan to review tomorrow morning.
Focus on: fast time-to-first-dollar, low setup cost, high leverage.

Categories to draw from (mix them):
1. Agentic micro-SaaS / info products (automated, minimal human ops)
2. Freelance/bounty gigs Clawmpson can research, apply for, and ship autonomously
3. Arbitrage bots (Polymarket, Kalshi, crypto DEX/CEX — paper-trade first)
4. Digital products / skills to sell on PromptBase, ClawMart, Gumroad, or similar
5. meOS / xyz.cards monetization angles (B2B, upsell, API)
6. AI agent services sold to small businesses (one-time or retainer)

For each idea, provide:
- **Title**: short name
- **What it is**: 1-2 sentences
- **Revenue model**: how money flows
- **Time to first dollar**: realistic estimate
- **First action**: the single next step Clawmpson can take autonomously
- **Risk/blocker**: biggest obstacle

Do NOT invent ideas already in this past list: ${PAST_IDEAS}
Current queue context: ${QUEUE}

Output in clean markdown with ## for each idea. Be specific — no vague 'build an AI tool' nonsense."

IDEAS=$(echo "$PROMPT" | ollama run llama3.3:70b 2>/dev/null || echo "$PROMPT" | ollama run qwen3:32b 2>/dev/null)
if [[ -z "$IDEAS" || "$IDEAS" == *"error"* ]]; then
  # Ollama down — attempt restart and retry
  ollama serve &>/dev/null &
  sleep 5
  IDEAS=$(echo "$PROMPT" | ollama run llama3.3:70b 2>/dev/null || echo "$PROMPT" | ollama run qwen3:32b 2>/dev/null)
  if [[ -z "$IDEAS" || "$IDEAS" == *"error"* ]]; then
    IDEAS="LLM unavailable — Ollama not responding (restart attempted, still down)"
    ESCALATION="🚨 CRITICAL: Ollama is DOWN — idea engine failed.
Restart attempted automatically but Ollama is still not responding.
Tier-2 escalation — requires manual intervention."
    bash "${OPENCLAW_ROOT}/scripts/notify-telegram.sh" "$ESCALATION" 2>/dev/null || true
    echo "{\"timestamp\":$(date +%s),\"check\":\"ollama\",\"status\":\"fail\",\"detail\":\"Idea engine Ollama failure — restart failed, Tier-2 escalated\"}" >> "${OPENCLAW_ROOT}/logs/ops-${TODAY}.jsonl"
  fi
fi

# --- Write output ---
cat > "$OUTPUT" << EOF
# Ideas Brief — ${TODAY}
> Generated by Clawmpson at $(date +"%H:%M"). 10 researched opportunities for Jordan's review.
> **Goal:** $10k/month. **Status:** $0 earned. Let's fix that.

${IDEAS}

---
*To approve an idea and push it to queue: reply to the Telegram message with the idea number.*
*Clawmpson will research further and build an action plan within 2 hours.*
EOF

# --- Telegram ping ---
SUMMARY=$(echo "$IDEAS" | grep "^## " | head -10 | nl -w2 -s'. ' | sed 's/## //')
MESSAGE="💡 Morning Ideas Brief — ${TODAY}

10 money-making ideas ready for review:
${SUMMARY}

Reply with number(s) to approve → I'll build action plans.
File: outputs/ideas-${TODAY}.md"

bash "${OPENCLAW_ROOT}/scripts/notify-telegram.sh" "$MESSAGE" 2>/dev/null || true

# --- Ingest into Ideas Lab dashboard ---
python3 "${OPENCLAW_ROOT}/scripts/idea-ingest.py" "${TODAY}" 2>/dev/null || true

# --- Log ---
echo "[${TODAY} 23:30] Idea engine ran — wrote ${OUTPUT}, ingested to Ideas Lab" >> "${OPENCLAW_ROOT}/memory/IDLE_LOG.md"
