#!/bin/bash
# cron-upstream-watch.sh — Daily upstream OpenClaw release monitor
# Schedule: 0 10 * * * (daily at 10am)
# Checks github.com/openclaw/openclaw for new releases, analyzes against our system

OPENCLAW_ROOT="${HOME}/openclaw"
TODAY=$(date +%Y-%m-%d)
LAST_CHECK_FILE="${OPENCLAW_ROOT}/memory/.upstream-last-tag"
OUTPUT_DIR="${OPENCLAW_ROOT}/autoresearch/outputs/briefs"

set -a; source "${OPENCLAW_ROOT}/.env" 2>/dev/null || true; set +a
mkdir -p "$OUTPUT_DIR"

# Get latest release tag
LATEST_TAG=$(gh api repos/openclaw/openclaw/releases/latest --jq '.tag_name' 2>/dev/null)
if [[ -z "$LATEST_TAG" ]]; then
  echo "[${TODAY}] Upstream check failed — gh API error" >> "${OPENCLAW_ROOT}/memory/IDLE_LOG.md"
  exit 0
fi

# Check if we've already analyzed this tag
LAST_TAG=$(cat "$LAST_CHECK_FILE" 2>/dev/null || echo "none")
if [[ "$LATEST_TAG" == "$LAST_TAG" ]]; then
  echo "[${TODAY}] Upstream check — no new release (still ${LATEST_TAG})" >> "${OPENCLAW_ROOT}/memory/IDLE_LOG.md"
  exit 0
fi

echo "[${TODAY}] New upstream release: ${LATEST_TAG} (was: ${LAST_TAG})" >> "${OPENCLAW_ROOT}/memory/IDLE_LOG.md"

# Fetch release notes
RELEASE_NOTES=$(gh api "repos/openclaw/openclaw/releases/tags/${LATEST_TAG}" --jq '.body' 2>/dev/null)
if [[ -z "$RELEASE_NOTES" ]]; then
  echo "[${TODAY}] Could not fetch release notes for ${LATEST_TAG}" >> "${OPENCLAW_ROOT}/memory/IDLE_LOG.md"
  exit 0
fi

# Trim to first 4000 chars for LLM context
NOTES_TRIMMED=$(echo "$RELEASE_NOTES" | head -c 4000)

# Our system context
OUR_STACK="Our OpenClaw system uses: Telegram bot (clawmson_chat.py, gemma4:e4b), 7 AI agents (AXIS/SCOUT/FORGE/VIGIL/WAVE/SHORE/VAULT), GonzoClaw dashboard (FastAPI+vanilla JS on port 7080), Cloudflare tunnel, 19 crons, Ollama local models (14 models ~264GB), MiroFish simulation, AutoResearch pipeline, trading bot (Polymarket), project-launch automation, Ralph build loop. We run on M2 Max 96GB with no cloud API dependency for core ops."

# Analyze with Ollama
ANALYSIS=$(echo "You are Clawmpson analyzing an upstream OpenClaw release for upgrade opportunities.

Release: ${LATEST_TAG}
Release notes (trimmed):
${NOTES_TRIMMED}

Our system:
${OUR_STACK}

Analyze this release and produce a brief with:

1. RELEVANT CHANGES (items that directly affect our Telegram bot, agents, memory, browser automation, or Ollama integration)
2. BREAKING CHANGES WE NEED TO HANDLE (if we update)
3. FEATURES TO CHERRY-PICK (things worth adopting without full upgrade)
4. SKIP (items irrelevant to our stack)
5. RECOMMENDATION: upgrade now / wait / cherry-pick specific items

Be specific. Reference our actual components." | ollama run gemma4:31b 2>/dev/null)

if [[ -z "$ANALYSIS" || "$ANALYSIS" == *"error"* ]]; then
  ANALYSIS="LLM unavailable — raw release notes saved. Review manually."
fi

# Strip think tags
ANALYSIS=$(echo "$ANALYSIS" | sed '/<think>/,/<\/think>/d')

# Write brief
BRIEF_FILE="${OUTPUT_DIR}/upstream-openclaw-${LATEST_TAG}-${TODAY}.md"
cat > "$BRIEF_FILE" << EOF
# Upstream OpenClaw Release Analysis: ${LATEST_TAG}
> Analyzed by Clawmpson on ${TODAY}
> Source: https://github.com/openclaw/openclaw/releases/tag/${LATEST_TAG}

---

${ANALYSIS}

---

## Raw Release Notes (first 2000 chars)

\`\`\`
$(echo "$RELEASE_NOTES" | head -c 2000)
\`\`\`

---
*Auto-generated by cron-upstream-watch.sh. Review on GonzoClaw RESEARCH tab.*
EOF

# Save last checked tag
echo "$LATEST_TAG" > "$LAST_CHECK_FILE"

# Telegram notification
bash "${OPENCLAW_ROOT}/scripts/notify-telegram.sh" "New upstream OpenClaw release: ${LATEST_TAG}

Analysis ready on GonzoClaw RESEARCH tab.
Brief: autoresearch/outputs/briefs/upstream-openclaw-${LATEST_TAG}-${TODAY}.md" 2>/dev/null || true

echo "[${TODAY}] Upstream analysis written: ${BRIEF_FILE}" >> "${OPENCLAW_ROOT}/memory/IDLE_LOG.md"
