#!/usr/bin/env bash
# Clawmpson daily trading log — generates report, commits + pushes
set -euo pipefail

OPENCLAW_DIR="$HOME/openclaw"
DB="$HOME/.openclaw/clawmson.db"
TODAY=$(date -u +%Y-%m-%d)
LOG_DIR="$OPENCLAW_DIR/logs"
REPORT="$LOG_DIR/trading-daily-$TODAY.md"

# Stats from paper_trades
balance=$(sqlite3 "$DB" "
    SELECT COALESCE(
        (SELECT value FROM context WHERE chat_id='mirofish' AND key='starting_balance'), '1000')
    " 2>/dev/null)
starting=${balance:-1000}
pnl=$(sqlite3 "$DB" "SELECT COALESCE(SUM(pnl), 0) FROM paper_trades WHERE status != 'open'" 2>/dev/null || echo "0")
current_bal=$(echo "$starting + $pnl" | bc 2>/dev/null || echo "$starting")
wins=$(sqlite3 "$DB" "SELECT COUNT(*) FROM paper_trades WHERE status='closed_win'" 2>/dev/null || echo "0")
losses=$(sqlite3 "$DB" "SELECT COUNT(*) FROM paper_trades WHERE status='closed_loss'" 2>/dev/null || echo "0")
open=$(sqlite3 "$DB" "SELECT COUNT(*) FROM paper_trades WHERE status='open'" 2>/dev/null || echo "0")

total=$((wins + losses))
if [ "$total" -gt 0 ]; then
    wr=$(echo "scale=1; $wins * 100 / $total" | bc)
else
    wr="0"
fi

# Per-strategy breakdown
strat_breakdown=$(sqlite3 -header -column "$DB" "
    SELECT strategy, COUNT(*) as trades,
           SUM(CASE WHEN status='closed_win' THEN 1 ELSE 0 END) as wins,
           ROUND(SUM(pnl), 2) as pnl
    FROM paper_trades WHERE status != 'open'
    GROUP BY strategy ORDER BY pnl DESC
" 2>/dev/null || echo "(none)")

# Recent trades
recent=$(sqlite3 -header -column "$DB" "
    SELECT question, direction, strategy, ROUND(pnl, 2) as pnl, status
    FROM paper_trades WHERE status != 'open'
    ORDER BY closed_at DESC LIMIT 10
" 2>/dev/null || echo "(none)")

cat > "$REPORT" <<REPORT
# Clawmpson Trading Daily — $TODAY

## Summary
| Metric | Value |
|--------|-------|
| Balance | \$$current_bal |
| Starting | \$$starting |
| PnL | \$$pnl |
| Win Rate | ${wr}% ($wins W / $losses L) |
| Open | $open |

## Strategy Breakdown
\`\`\`
$strat_breakdown
\`\`\`

## Recent Trades
\`\`\`
$recent
\`\`\`

---
*Auto-generated by cron-daily-trading-log.sh*
REPORT

echo "[clawmpson] Trading report: $REPORT"

# Commit and push
cd "$OPENCLAW_DIR"
git add logs/trading-daily-*.md logs/arbclaw.log logs/fast-scan.log logs/crypto-spot.log logs/math-strategies.log logs/mirofish.log 2>/dev/null || true
git commit -m "daily trading log $TODAY — bal=\$$current_bal W:$wins L:$losses

Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>" 2>/dev/null || echo "No changes"
git push origin main 2>/dev/null || git push 2>/dev/null || echo "Push failed"
